import type { SiteContent } from '@/types';

/**
 * Демо-контент BENCH.
 * Використовується, коли Supabase ще не підключено — сайт одразу виглядає живим.
 * Фото — з Unsplash (ліниве завантаження через next/image).
 */

const img = (id: string, w = 800) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=70`;

export const demoContent: SiteContent = {
  live: false,
  settings: {
    name: 'КАВОВА',
    tagline: 'кав’ярня',
    description:
      'КАВОВА — затишна кав’ярня у Дніпрі на Слобожанському проспекті. Добірне зерно, свіжа випічка та тепле світло — місце, куди хочеться повертатися.',
    heroTitle: 'Кава, до якої хочеться повертатися',
    heroSubtitle:
      'Повільна обжарка, чесний смак і місце, де приємно посидіти. Заходьте на каву — і залишайтеся на розмову.',
    heroImage: img('1442512595331-e89e73853f31', 1600),
    address: 'проспект Слобожанський, 67к, Дніпро, 49000',
    // Телефон-заповнювач — змініть у /admin або тут.
    phone: '+380 67 000 00 00',
    hours: 'Пн–Пт 08:00–21:00 · Сб–Нд 09:00–22:00',
    instagram: 'https://www.instagram.com/kavova.ua',
    mapsUrl: `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(
      'проспект Слобожанський, 67к, Дніпро',
    )}`,
    mapEmbed: `https://maps.google.com/maps?q=${encodeURIComponent(
      'проспект Слобожанський, 67к, Дніпро',
    )}&z=16&output=embed`,
    lat: 48.5127,
    lng: 35.0975,
  },
  categories: [
    { slug: 'coffee', name: 'Кава', sortOrder: 1 },
    { slug: 'tea', name: 'Чай', sortOrder: 2 },
    { slug: 'breakfast', name: 'Сніданки', sortOrder: 3 },
    { slug: 'desserts', name: 'Десерти', sortOrder: 4 },
    { slug: 'bakery', name: 'Випічка', sortOrder: 5 },
  ],
  menu: [
    // ── Кава ──
    {
      id: 'm-espresso',
      categorySlug: 'coffee',
      name: 'Еспресо',
      description: 'Щільна крема, темні ягоди та какао. Наша базова обжарка.',
      price: 55,
      image: img('1510591509098-f4fdc6d0ff04'),
      badges: ['hit'],
      sortOrder: 1,
      available: true,
    },
    {
      id: 'm-cappuccino',
      categorySlug: 'coffee',
      name: 'Капучино',
      description: 'Оксамитова молочна піна й баланс солодкої карамелі.',
      price: 70,
      image: img('1572442388796-11668a67e53d'),
      badges: ['hit'],
      sortOrder: 2,
      available: true,
    },
    {
      id: 'm-latte',
      categorySlug: 'coffee',
      name: 'Флет вайт',
      description: 'Подвійний рістретто та мікропіна — мʼяко й насичено.',
      price: 75,
      image: img('1517701550927-30cf4ba1dba5'),
      badges: [],
      sortOrder: 3,
      available: true,
    },
    {
      id: 'm-filter',
      categorySlug: 'coffee',
      name: 'Фільтр V60',
      description: 'Сезонне зерно альтернативної обжарки. Чисто й ароматно.',
      price: 90,
      image: img('1495474472287-4d71bcdd2085'),
      badges: ['new'],
      sortOrder: 4,
      available: true,
    },
    {
      id: 'm-raf',
      categorySlug: 'coffee',
      name: 'Раф лавандовий',
      description: 'Ніжний вершковий раф із ноткою лаванди.',
      price: 85,
      image: img('1461023058943-07fcbe16d735'),
      badges: ['new'],
      sortOrder: 5,
      available: true,
    },
    // ── Чай ──
    {
      id: 't-sencha',
      categorySlug: 'tea',
      name: 'Сенча',
      description: 'Японський зелений чай — свіжий, трав’яний, легкий.',
      price: 60,
      image: img('1556679343-c7306c1976bc'),
      badges: [],
      sortOrder: 1,
      available: true,
    },
    {
      id: 't-berry',
      categorySlug: 'tea',
      name: 'Ягідний глінтвейн-чай',
      description: 'Гарячий настій обліпихи, малини та спецій.',
      price: 75,
      image: img('1597481499750-3e6b22637e12'),
      badges: ['hit'],
      sortOrder: 2,
      available: true,
    },
    // ── Сніданки ──
    {
      id: 'b-avocado',
      categorySlug: 'breakfast',
      name: 'Тост з авокадо',
      description: 'Житній хліб, авокадо, яйце пашот, мікрозелень.',
      price: 165,
      image: img('1525351484163-7529414344d8'),
      badges: ['hit'],
      sortOrder: 1,
      available: true,
    },
    {
      id: 'b-granola',
      categorySlug: 'breakfast',
      name: 'Гранола з йогуртом',
      description: 'Домашня гранола, грецький йогурт, сезонні ягоди, мед.',
      price: 130,
      image: img('1490474418585-ba9bad8fd0ea'),
      badges: [],
      sortOrder: 2,
      available: true,
    },
    {
      id: 'b-eggs',
      categorySlug: 'breakfast',
      name: 'Яйця Бенедикт',
      description: 'Бріош, шинка, яйця пашот, голландський соус.',
      price: 185,
      image: img('1608039829572-78524f79c4c7'),
      badges: ['new'],
      sortOrder: 3,
      available: true,
    },
    // ── Десерти ──
    {
      id: 'd-cheesecake',
      categorySlug: 'desserts',
      name: 'Нью-йоркський чізкейк',
      description: 'Класичний вершковий чізкейк на пісочній основі.',
      price: 120,
      image: img('1533134242443-d4fd215305ad'),
      badges: ['hit'],
      sortOrder: 1,
      available: true,
    },
    {
      id: 'd-tiramisu',
      categorySlug: 'desserts',
      name: 'Тірамісу',
      description: 'Савоярді, маскарпоне й еспресо нашої обжарки.',
      price: 135,
      image: img('1571877227200-a0d98ea607e9'),
      badges: [],
      sortOrder: 2,
      available: true,
    },
    // ── Випічка ──
    {
      id: 'p-croissant',
      categorySlug: 'bakery',
      name: 'Круасан вершковий',
      description: 'Листкове тісто на бельгійському маслі. Випікаємо щоранку.',
      price: 65,
      image: img('1509440159596-0249088772ff'),
      badges: ['hit'],
      sortOrder: 1,
      available: true,
    },
    {
      id: 'p-cinnamon',
      categorySlug: 'bakery',
      name: 'Синабон з корицею',
      description: 'Мʼяка булочка з корицею та вершковою глазур’ю.',
      price: 85,
      image: img('1509365465985-25d11c17e812'),
      badges: ['new'],
      sortOrder: 2,
      available: true,
    },
    {
      id: 'p-cookie',
      categorySlug: 'bakery',
      name: 'Печиво з шоколадом',
      description: 'Хрустке зовні, тягуче всередині, з бельгійським шоколадом.',
      price: 55,
      image: img('1499636136210-6f4ee915583e'),
      badges: [],
      sortOrder: 3,
      available: true,
    },
  ],
  gallery: [
    { id: 'g1', url: img('1554118811-1e0d58224f24', 900), alt: 'Затишний інтер’єр кав’ярні BENCH', sortOrder: 1 },
    { id: 'g2', url: img('1521017432531-fbd92d768814', 900), alt: 'Бариста готує каву', sortOrder: 2 },
    { id: 'g3', url: img('1447933601403-0c6688de566e', 900), alt: 'Чашка кави з латте-артом', sortOrder: 3 },
    { id: 'g4', url: img('1495474472287-4d71bcdd2085', 900), alt: 'Альтернативне заварювання', sortOrder: 4 },
    { id: 'g5', url: img('1509440159596-0249088772ff', 900), alt: 'Свіжа випічка', sortOrder: 5 },
    { id: 'g6', url: img('1445116572660-236099ec97a0', 900), alt: 'Сніданок на дерев’яному столі', sortOrder: 6 },
    { id: 'g7', url: img('1453614512568-c4024d13c247', 900), alt: 'Кавові зерна', sortOrder: 7 },
    { id: 'g8', url: img('1481833761820-0509d3217039', 900), alt: 'Тепле світло у залі', sortOrder: 8 },
  ],
  reviews: [
    {
      id: 'r1',
      name: 'Олена',
      rating: 5,
      text: 'Найкращий флет вайт у місті. Атмосфера така, що не хочеться йти. Повертаюся щоранку.',
      approved: true,
      createdAt: '2026-05-12T09:20:00Z',
    },
    {
      id: 'r2',
      name: 'Андрій',
      rating: 5,
      text: 'Круасани — окрема любов. Тепле світло, приємна музика, привітні баристи.',
      approved: true,
      createdAt: '2026-05-28T14:05:00Z',
    },
    {
      id: 'r3',
      name: 'Марія',
      rating: 4,
      text: 'Дуже смачна фільтр-кава і чудові сніданки. У вихідні буває людно, але воно того варте.',
      approved: true,
      createdAt: '2026-06-03T11:40:00Z',
    },
    {
      id: 'r4',
      name: 'Дмитро',
      rating: 5,
      text: 'Ідеальне місце попрацювати з ноутбуком за чашкою рафу. Wi-Fi та розетки — велике дякую.',
      approved: true,
      createdAt: '2026-06-19T16:15:00Z',
    },
  ],
};
