// АВТОГЕНЕРОВАНО з меню КАВОВА (джерело — menu.csv). Реальні фото додаються через /admin.
import type { MenuCategory, MenuItem } from '@/types';

export const kavovaCategories: MenuCategory[] = [
  { slug: 'ice', name: 'ICE MENU', sortOrder: 1 },
  { slug: 'hot', name: 'HOT DRINKS', sortOrder: 2 },
  { slug: 'seasonal', name: 'Сезонні напої', sortOrder: 3 },
  { slug: 'cold', name: 'COLD DRINKS', sortOrder: 4 },
  { slug: 'bakery', name: 'BAKERY', sortOrder: 5 },
  { slug: 'food', name: 'FOOD', sortOrder: 6 },
  { slug: 'bar', name: 'KABOBA BAR', sortOrder: 7 },
  { slug: 'wine', name: 'КАВОВА WINE', sortOrder: 8 },
];

export const kavovaMenu: MenuItem[] = [
  { id: 'ice-0', categorySlug: 'ice', name: 'Бамбл', group: 'Кава', description: '', price: 95, image: '/menu/ice-0.png', badges: [], sortOrder: 1, available: true },
  { id: 'ice-1', categorySlug: 'ice', name: 'Айс матча лате', group: 'Матча', description: '', price: 155, image: '/menu/ice-1.jpeg', badges: [], sortOrder: 2, available: true },
  { id: 'ice-2', categorySlug: 'ice', name: 'Айс Какао', group: 'Не кава', description: '', price: 95, image: '', badges: [], sortOrder: 3, available: true },
  { id: 'ice-3', categorySlug: 'ice', name: 'Еспресо-тонік', group: 'Кава', description: '', price: 95, image: '', badges: [], sortOrder: 4, available: true },
  { id: 'ice-4', categorySlug: 'ice', name: 'Банана матча', group: 'Матча', description: '', price: 155, image: '/menu/ice-4.jpeg', badges: [], sortOrder: 5, available: true },
  { id: 'ice-5', categorySlug: 'ice', name: 'Айс Ті', group: 'Не кава', description: '', price: 95, image: '/menu/ice-5.jpeg', badges: [], sortOrder: 6, available: true },
  { id: 'ice-6', categorySlug: 'ice', name: 'Айс Лате', group: 'Кава', description: '', price: 95, image: '/menu/ice-6.jpeg', badges: [], sortOrder: 7, available: true },
  { id: 'ice-7', categorySlug: 'ice', name: 'Матча Тонік', group: 'Матча', description: '', price: 155, image: '/menu/ice-7.jpeg', badges: [], sortOrder: 8, available: true },
  { id: 'ice-8', categorySlug: 'ice', name: 'Лимонад', group: 'Не кава', description: 'класичний | мохіто | санрайз | грейпфрут-розмарин', price: 95, image: '/menu/ice-8.jpeg', badges: [], sortOrder: 9, available: true },
  { id: 'ice-9', categorySlug: 'ice', name: 'Айріш кава', group: 'Кава', description: '', price: 155, image: '', badges: [], sortOrder: 10, available: true },
  { id: 'ice-10', categorySlug: 'ice', name: 'Матча Оранж', group: 'Матча', description: '', price: 155, image: '/menu/ice-10.png', badges: [], sortOrder: 11, available: true },
  { id: 'ice-11', categorySlug: 'ice', name: 'Мілкшейк', group: 'Не кава', description: '', price: 155, image: '/menu/ice-11.jpeg', badges: [], sortOrder: 12, available: true },
  { id: 'ice-12', categorySlug: 'ice', name: 'Афогато', group: 'Кава', description: '', price: 95, image: '/menu/ice-12.jpeg', badges: [], sortOrder: 13, available: true },
  { id: 'bar-13', categorySlug: 'bar', name: 'Келих просекко', group: 'Келих', description: '', price: 155, image: '', badges: [], sortOrder: 1, available: true },
  { id: 'bar-14', categorySlug: 'bar', name: 'Келих вина', group: 'Келих', description: '', price: 75, image: '', badges: [], sortOrder: 2, available: true },
  { id: 'bar-15', categorySlug: 'bar', name: 'Gin Tonic', group: 'Коктейлі', description: 'Джин, Schweppes, тонік, лайм, лід', price: 185, image: '', badges: [], sortOrder: 3, available: true },
  { id: 'bar-16', categorySlug: 'bar', name: 'Pornstar', group: 'Коктейлі', description: '', price: 255, image: '/menu/bar-16.jpeg', badges: [], sortOrder: 4, available: true },
  { id: 'bar-17', categorySlug: 'bar', name: 'Aperol Spritz', group: 'Коктейлі', description: '', price: 255, image: '/menu/bar-17.jpeg', badges: [], sortOrder: 5, available: true },
  { id: 'bar-18', categorySlug: 'bar', name: 'Mojito', group: 'Коктейлі', description: '', price: 185, image: '/menu/bar-18.jpeg', badges: [], sortOrder: 6, available: true },
  { id: 'bar-19', categorySlug: 'bar', name: 'Sunrise', group: 'Коктейлі', description: '', price: 185, image: '/menu/bar-19.jpeg', badges: [], sortOrder: 7, available: true },
  { id: 'bar-20', categorySlug: 'bar', name: 'Strawberry Gin Tonic Beefeater', group: 'Коктейлі', description: '', price: 185, image: '/menu/bar-20.jpeg', badges: [], sortOrder: 8, available: true },
  { id: 'bar-21', categorySlug: 'bar', name: 'Orange Gin Tonic Beefeater', group: 'Коктейлі', description: '', price: 185, image: '/menu/bar-21.jpeg', badges: [], sortOrder: 9, available: true },
  { id: 'bar-22', categorySlug: 'bar', name: 'Gin Garden Beefeater', group: 'Коктейлі', description: '', price: 185, image: '/menu/bar-22.jpeg', badges: [], sortOrder: 10, available: true },
  { id: 'bar-23', categorySlug: 'bar', name: 'Gin Garden Beefeater N/A', group: 'Коктейлі', description: '', price: 185, image: '/menu/bar-23.jpeg', badges: [], sortOrder: 11, available: true },
  { id: 'hot-24', categorySlug: 'hot', name: 'Чай натуральний', group: 'Чай to go', description: '', price: 85, image: '', badges: [], sortOrder: 1, available: true },
  { id: 'hot-25', categorySlug: 'hot', name: 'Какао', group: 'НЕ КАВА', description: '', price: 70, image: '', badges: [], sortOrder: 2, available: true },
  { id: 'hot-26', categorySlug: 'hot', name: 'Еспресо', group: 'ЧОРНА КАВА', description: '', price: 55, image: '', badges: [], sortOrder: 3, available: true },
  { id: 'hot-27', categorySlug: 'hot', name: 'Американо з молоком', group: 'БІЛА КАВА', description: '', price: 60, image: '', badges: [], sortOrder: 4, available: true },
  { id: 'hot-28', categorySlug: 'hot', name: 'Рослинне', group: 'Молоко', description: '', price: 30, image: '', badges: [], sortOrder: 5, available: true },
  { id: 'hot-29', categorySlug: 'hot', name: 'Допіо', group: 'ЧОРНА КАВА', description: '', price: 75, image: '', badges: [], sortOrder: 6, available: true },
  { id: 'hot-30', categorySlug: 'hot', name: 'Макіато', group: 'БІЛА КАВА', description: '', price: 60, image: '', badges: [], sortOrder: 7, available: true },
  { id: 'hot-31', categorySlug: 'hot', name: 'Безлактозне', group: 'Молоко', description: '', price: 20, image: '', badges: [], sortOrder: 8, available: true },
  { id: 'hot-32', categorySlug: 'hot', name: 'Американо', group: 'ЧОРНА КАВА', description: '', price: 55, image: '', badges: [], sortOrder: 9, available: true },
  { id: 'hot-33', categorySlug: 'hot', name: 'Какао', group: 'НЕ КАВА', description: '', price: 90, image: '', badges: [], sortOrder: 10, available: true },
  { id: 'hot-34', categorySlug: 'hot', name: 'Блек Кава', group: 'ЧОРНА КАВА', description: '', price: 75, image: '', badges: [], sortOrder: 11, available: true },
  { id: 'hot-35', categorySlug: 'hot', name: 'Лате', group: 'БІЛА КАВА', description: '', price: 70, image: '', badges: [], sortOrder: 12, available: true },
  { id: 'hot-36', categorySlug: 'hot', name: 'Фільтр', group: 'ЧОРНА КАВА', description: '', price: 85, image: '', badges: [], sortOrder: 13, available: true },
  { id: 'hot-37', categorySlug: 'hot', name: 'Лате', group: 'БІЛА КАВА', description: '', price: 85, image: '', badges: [], sortOrder: 14, available: true },
  { id: 'hot-38', categorySlug: 'hot', name: 'Чай пакетований', group: 'Чай to go', description: 'трав\'яний, фруктовий, чорний, зелений', price: 55, image: '', badges: [], sortOrder: 15, available: true },
  { id: 'hot-39', categorySlug: 'hot', name: 'Чай натуральний', group: 'Чай в кавʼярні', description: '', price: 145, image: '', badges: [], sortOrder: 16, available: true },
  { id: 'hot-40', categorySlug: 'hot', name: 'Маття', group: 'НЕ КАВА', description: '', price: 70, image: '', badges: [], sortOrder: 17, available: true },
  { id: 'hot-41', categorySlug: 'hot', name: 'Капучино', group: 'БІЛА КАВА', description: '', price: 65, image: '', badges: [], sortOrder: 18, available: true },
  { id: 'hot-42', categorySlug: 'hot', name: 'Капучино', group: 'БІЛА КАВА', description: '', price: 80, image: '', badges: [], sortOrder: 19, available: true },
  { id: 'hot-43', categorySlug: 'hot', name: 'Чай чорний', group: 'Чай в кавʼярні', description: '', price: 90, image: '', badges: [], sortOrder: 20, available: true },
  { id: 'hot-44', categorySlug: 'hot', name: 'Флет вайт', group: 'БІЛА КАВА', description: '', price: 75, image: '', badges: [], sortOrder: 21, available: true },
  { id: 'hot-45', categorySlug: 'hot', name: 'Чай зелений', group: 'Чай в кавʼярні', description: '', price: 90, image: '', badges: [], sortOrder: 22, available: true },
  { id: 'hot-46', categorySlug: 'hot', name: 'Лимон до чаю', group: 'Чай to go', description: '', price: 10, image: '', badges: [], sortOrder: 23, available: true },
  { id: 'hot-47', categorySlug: 'hot', name: 'Раф класичний', group: 'БІЛА КАВА', description: '', price: 90, image: '', badges: [], sortOrder: 24, available: true },
  { id: 'hot-48', categorySlug: 'hot', name: 'Склянка молока', group: 'БІЛА КАВА', description: '', price: 45, image: '', badges: [], sortOrder: 25, available: true },
  { id: 'bakery-49', categorySlug: 'bakery', name: 'Печиво кокосове', group: 'COOKIE (печиво, трубочка, горішки)', description: 'Кокосове печиво без додавання муки', price: 35, image: '', badges: [], sortOrder: 1, available: true },
  { id: 'bakery-50', categorySlug: 'bakery', name: 'Дорблю-Груша', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-50.jpeg', badges: [], sortOrder: 2, available: true },
  { id: 'bakery-51', categorySlug: 'bakery', name: 'Десерт Чіа манго', group: 'TRIFLE (десерти в стаканчику)', description: 'Семена чіа на кокосовом молоці з пюре манго-маракуя', price: 125, image: '', badges: [], sortOrder: 3, available: true },
  { id: 'bakery-52', categorySlug: 'bakery', name: 'Еклери', group: 'CAKE (торт і тістечко)', description: 'Заварні тістечка з різноманітними начинками. Манго |Фісташка|Мигдаль|Шоколад', price: 85, image: '', badges: [], sortOrder: 4, available: true },
  { id: 'bakery-53', categorySlug: 'bakery', name: 'Диня-Дорблю', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-53.jpeg', badges: [], sortOrder: 5, available: true },
  { id: 'bakery-54', categorySlug: 'bakery', name: 'Вишневий чізкейк в стаканчику', group: 'TRIFLE (десерти в стаканчику)', description: 'Шоколадний бісквіт | Вишневий Чізкейк | Крем Чіз | Вишневе компоті', price: 125, image: '', badges: [], sortOrder: 6, available: true },
  { id: 'bakery-55', categorySlug: 'bakery', name: 'Печиво шоколад вишня', group: 'COOKIE (печиво, трубочка, горішки)', description: 'Печиво на основі брауні з шоколадом, кавою та вишнею', price: 65, image: '', badges: [], sortOrder: 7, available: true },
  { id: 'bakery-56', categorySlug: 'bakery', name: 'Macarons mono', group: 'MACAROONS', description: '', price: 85, image: '', badges: [], sortOrder: 8, available: true },
  { id: 'bakery-57', categorySlug: 'bakery', name: 'Тірамісу десерт', group: 'TRIFLE (десерти в стаканчику)', description: 'Вершковий сир Маскарпоне | Печиво Савоярді | Кава | Амаретто', price: 125, image: '', badges: [], sortOrder: 9, available: true },
  { id: 'bakery-58', categorySlug: 'bakery', name: 'Печиво вівсяне', group: 'COOKIE (печиво, трубочка, горішки)', description: 'Цільнозернове натуральне печиво з журавлиною', price: 35, image: '', badges: [], sortOrder: 10, available: true },
  { id: 'bakery-59', categorySlug: 'bakery', name: 'Наполеон класика', group: 'CAKE (торт і тістечко)', description: 'Супер кремовий класичний торт', price: 75, image: '', badges: [], sortOrder: 11, available: true },
  { id: 'bakery-60', categorySlug: 'bakery', name: 'Горгонзола-Журавлина', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-60.jpeg', badges: [], sortOrder: 12, available: true },
  { id: 'bakery-61', categorySlug: 'bakery', name: 'Снікерс десерт', group: 'TRIFLE (десерти в стаканчику)', description: 'Шоколадний бісквіт | Карамельний чізкейк, Вершковий крем | Карамель | Арахіс', price: 125, image: '', badges: [], sortOrder: 13, available: true },
  { id: 'bakery-62', categorySlug: 'bakery', name: 'Банановий Раф', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-62.jpeg', badges: [], sortOrder: 14, available: true },
  { id: 'bakery-63', categorySlug: 'bakery', name: 'Наполеон десерт в стаканчику', group: 'TRIFLE (десерти в стаканчику)', description: 'Листкове тісто | Заварний крем | Згущене молоко', price: 125, image: '', badges: [], sortOrder: 15, available: true },
  { id: 'bakery-64', categorySlug: 'bakery', name: 'Трубочка сгущенка', group: 'COOKIE (печиво, трубочка, горішки)', description: 'Трубочка з масляним кремом на основі вареного згущеного молока', price: 75, image: '', badges: [], sortOrder: 16, available: true },
  { id: 'bakery-65', categorySlug: 'bakery', name: 'Малинове морозиво', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-65.jpeg', badges: [], sortOrder: 17, available: true },
  { id: 'bakery-66', categorySlug: 'bakery', name: 'Горішок з ірискою', group: 'COOKIE (печиво, трубочка, горішки)', description: 'Класичний горішок з ірискою', price: 25, image: '', badges: [], sortOrder: 18, available: true },
  { id: 'bakery-67', categorySlug: 'bakery', name: 'Кейк-попс', group: 'CAKE (торт і тістечко)', description: '', price: 75, image: '', badges: [], sortOrder: 19, available: true },
  { id: 'bakery-68', categorySlug: 'bakery', name: 'Вишня у шоколаді', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-68.jpeg', badges: [], sortOrder: 20, available: true },
  { id: 'bakery-69', categorySlug: 'bakery', name: 'Три молока десерт в стаканчику', group: 'TRIFLE (десерти в стаканчику)', description: 'Мигдалевий бісквіт, пропитаний: топлене молоко, згущене та варене згущене молоко | Крем Чіз', price: 125, image: '', badges: [], sortOrder: 21, available: true },
  { id: 'bakery-70', categorySlug: 'bakery', name: 'Кава-Бейліс', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-70.jpeg', badges: [], sortOrder: 22, available: true },
  { id: 'bakery-71', categorySlug: 'bakery', name: 'Орео десерт', group: 'TRIFLE (десерти в стаканчику)', description: 'Шоколадний бісквіт | Крем Чіз | печиво Орео', price: 125, image: '', badges: [], sortOrder: 23, available: true },
  { id: 'bakery-72', categorySlug: 'bakery', name: 'Лайм-Полуниця', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-72.jpeg', badges: [], sortOrder: 24, available: true },
  { id: 'bakery-73', categorySlug: 'bakery', name: 'Баунті', group: 'TRIFLE (десерти в стаканчику)', description: 'Шоколадний бісквіт | Крем чиз | Кокос | Бельгійський шоколад', price: 125, image: '', badges: [], sortOrder: 25, available: true },
  { id: 'bakery-74', categorySlug: 'bakery', name: 'Шу ванільний', group: 'CAKE (торт і тістечко)', description: '', price: 85, image: '', badges: [], sortOrder: 26, available: true },
  { id: 'bakery-75', categorySlug: 'bakery', name: 'Фісташка-Малина', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-75.jpeg', badges: [], sortOrder: 27, available: true },
  { id: 'bakery-76', categorySlug: 'bakery', name: 'Печиво бискоті', group: 'COOKIE (печиво, трубочка, горішки)', description: '', price: 35, image: '', badges: [], sortOrder: 28, available: true },
  { id: 'bakery-77', categorySlug: 'bakery', name: 'Кекс апельсин/морквяний', group: 'CAKE (торт і тістечко)', description: '', price: 85, image: '', badges: [], sortOrder: 29, available: true },
  { id: 'bakery-78', categorySlug: 'bakery', name: 'Кіндер', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-78.jpeg', badges: [], sortOrder: 30, available: true },
  { id: 'bakery-79', categorySlug: 'bakery', name: 'Твікс', group: 'TRIFLE (десерти в стаканчику)', description: '', price: 125, image: '', badges: [], sortOrder: 31, available: true },
  { id: 'bakery-80', categorySlug: 'bakery', name: 'Пряник імбирний', group: 'COOKIE (печиво, трубочка, горішки)', description: '', price: 45, image: '', badges: [], sortOrder: 32, available: true },
  { id: 'bakery-81', categorySlug: 'bakery', name: 'Буено', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-81.jpeg', badges: [], sortOrder: 33, available: true },
  { id: 'bakery-82', categorySlug: 'bakery', name: 'Червоний оксамит', group: 'TRIFLE (десерти в стаканчику)', description: '', price: 125, image: '', badges: [], sortOrder: 34, available: true },
  { id: 'bakery-83', categorySlug: 'bakery', name: 'Пломбір-Лохина', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-83.jpeg', badges: [], sortOrder: 35, available: true },
  { id: 'bakery-84', categorySlug: 'bakery', name: 'Кокосовий Лате', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-84.jpeg', badges: [], sortOrder: 36, available: true },
  { id: 'bakery-85', categorySlug: 'bakery', name: 'Фундук-Шоколад', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-85.jpeg', badges: [], sortOrder: 37, available: true },
  { id: 'bakery-86', categorySlug: 'bakery', name: 'Лате-Гудбрандсдален', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-86.jpeg', badges: [], sortOrder: 38, available: true },
  { id: 'bakery-87', categorySlug: 'bakery', name: 'Рафаелло', group: 'MACAROONS', description: '', price: 115, image: '/menu/bakery-87.jpeg', badges: [], sortOrder: 39, available: true },
  { id: 'bakery-88', categorySlug: 'bakery', name: 'Канеле', group: 'CAKE (торт і тістечко)', description: '', price: 45, image: '', badges: [], sortOrder: 40, available: true },
  { id: 'bakery-89', categorySlug: 'bakery', name: 'Macarons Sweet', group: 'MACAROONS', description: '', price: 115, image: '', badges: [], sortOrder: 41, available: true },
  { id: 'bakery-90', categorySlug: 'bakery', name: 'Круасан мигдалевий', group: 'CAKE (торт і тістечко)', description: '', price: 155, image: '', badges: [], sortOrder: 42, available: true },
  { id: 'food-91', categorySlug: 'food', name: 'Сендвіч з куркою', group: 'Сендвічі', description: 'Сендвіч з куркою, зі свіжим огірком та двома видами сиру', price: 115, image: '/menu/food-91.png', badges: [], sortOrder: 1, available: true },
  { id: 'food-92', categorySlug: 'food', name: 'Cалат Цезар', group: 'Салати', description: '', price: 155, image: '/menu/food-92.jpeg', badges: [], sortOrder: 2, available: true },
  { id: 'food-93', categorySlug: 'food', name: 'Круасан з лососем', group: 'Круасани', description: '', price: 155, image: '/menu/food-93.jpeg', badges: [], sortOrder: 3, available: true },
  { id: 'food-94', categorySlug: 'food', name: 'Круасан з шинкою', group: 'Круасани', description: '', price: 155, image: '/menu/food-94.jpeg', badges: [], sortOrder: 4, available: true },
  { id: 'food-95', categorySlug: 'food', name: 'Сендвіч з куркою (велика)', group: 'Сендвічі', description: '', price: 195, image: '/menu/food-95.png', badges: [], sortOrder: 5, available: true },
  { id: 'food-96', categorySlug: 'food', name: 'Сендвіч з телятиною', group: 'Сендвічі', description: '', price: 195, image: '', badges: [], sortOrder: 6, available: true },
  { id: 'food-97', categorySlug: 'food', name: 'Кіш курка', group: 'Сендвічі', description: '', price: 95, image: '', badges: [], sortOrder: 7, available: true },
  { id: 'food-98', categorySlug: 'food', name: 'Кіш тунець', group: 'Сендвічі', description: '', price: 95, image: '/menu/food-98.jpeg', badges: [], sortOrder: 8, available: true },
  { id: 'wine-99', categorySlug: 'wine', name: 'Асті виноградне натуральне ігристе біле солодке вино Canti 0,75 л', group: 'Ігристе вино', description: '', price: 595, image: '', badges: [], sortOrder: 1, available: true },
  { id: 'wine-100', categorySlug: 'wine', name: 'Вайт-Семі-Світ напівсолодке біле вино натуральне виноградне Baron Simon 0,75л', group: 'Біле вино', description: '', price: 255, image: '', badges: [], sortOrder: 2, available: true },
  { id: 'wine-101', categorySlug: 'wine', name: 'Bино Вайт-Семі-Світ, Baron Simon напівсолодке червоне 0,75 л', group: 'Червоне вино', description: '', price: 255, image: '', badges: [], sortOrder: 3, available: true },
  { id: 'wine-102', categorySlug: 'wine', name: 'Матеус Розе вино напівсухе рожеве натуральне 0,75л', group: 'Рожеве вино', description: '', price: 355, image: '', badges: [], sortOrder: 4, available: true },
  { id: 'wine-103', categorySlug: 'wine', name: 'Асті ігристе біле солодке вино Canti 200 мл', group: 'Ігристе вино', description: '', price: 255, image: '', badges: [], sortOrder: 5, available: true },
  { id: 'wine-104', categorySlug: 'wine', name: 'Каппо Москато натуральне сухе біле вино виноградне J.Garcia Carrion, 0,75л', group: 'Біле вино', description: '', price: 255, image: '', badges: [], sortOrder: 6, available: true },
  { id: 'wine-105', categorySlug: 'wine', name: 'Монтепульчано ДʼАбруццо вино сухе червоне натуральне виноградне DOC 11.11.11. 0,75л', group: 'Червоне вино', description: '', price: 255, image: '', badges: [], sortOrder: 7, available: true },
  { id: 'wine-106', categorySlug: 'wine', name: 'Ламбруско дель Емілія Бʼянка вино напівігристе напівсолодке біле 0,75л', group: 'Ігристе вино', description: '', price: 395, image: '', badges: [], sortOrder: 8, available: true },
  { id: 'wine-107', categorySlug: 'wine', name: 'Ля Вʼєм Ферм вино сухе біле натуральне Perrin et Fils 0,75 л', group: 'Біле вино', description: '', price: 465, image: '', badges: [], sortOrder: 9, available: true },
  { id: 'wine-108', categorySlug: 'wine', name: 'Пино Нуар Pete\'s Pure Вино сухе червоне натуральне виноградне 0,75л', group: 'Червоне вино', description: '', price: 695, image: '', badges: [], sortOrder: 10, available: true },
  { id: 'wine-109', categorySlug: 'wine', name: 'Міллезімато ігристе екстра сухе біле Просекко 200 мл Canti', group: 'Ігристе вино', description: '', price: 255, image: '', badges: [], sortOrder: 11, available: true },
  { id: 'wine-110', categorySlug: 'wine', name: 'Пино Гріджио біле сухе натуральне 11.11.11. 0,75л', group: 'Біле вино', description: '', price: 255, image: '', badges: [], sortOrder: 12, available: true },
  { id: 'wine-111', categorySlug: 'wine', name: 'Міллезімато Розе екстра-сухе Просекко 200 мл Canti', group: 'Ігристе вино', description: '', price: 255, image: '', badges: [], sortOrder: 13, available: true },
  { id: 'wine-112', categorySlug: 'wine', name: 'Піно Гріджіо біле сухе вино натуральне виноградне delle Venezia DOC, Cesari 0,75 л', group: 'Біле вино', description: '', price: 465, image: '', badges: [], sortOrder: 14, available: true },
  { id: 'wine-113', categorySlug: 'wine', name: 'Просєко Вілла Йоланда ігристе екстра сухе біле 750 мл', group: 'Ігристе вино', description: '', price: 595, image: '', badges: [], sortOrder: 15, available: true },
  { id: 'wine-114', categorySlug: 'wine', name: 'Совіньйон Блан сухе біле натуральне виноградне Sant Clair 0,75л', group: 'Біле вино', description: '', price: 655, image: '', badges: [], sortOrder: 16, available: true },
  { id: 'wine-115', categorySlug: 'wine', name: 'Шардоне Мальборо вино сухе біле натуральне, Saint Clair 0,75 л', group: 'Біле вино', description: '', price: 655, image: '', badges: [], sortOrder: 17, available: true },
  { id: 'cold-116', categorySlug: 'cold', name: 'Комбуча Sachi', group: 'Комбуча', description: 'скло. Лемонграс, гібіскус і годжі, мате з мʼятою, яблуко, класична, жасмин, манго', price: 85, image: '', badges: [], sortOrder: 1, available: true },
  { id: 'seasonal-117', categorySlug: 'seasonal', name: 'Вишневий какао', group: 'ГАРЯЧІ СЕЗОННІ НАПОІ', description: '', price: 95, image: '/menu/seasonal-117.jpeg', badges: [], sortOrder: 1, available: true },
  { id: 'seasonal-118', categorySlug: 'seasonal', name: 'Глінтвейн', group: 'АЛКОГОЛЬНІ ГАРЯЧІ НАПОІ', description: '', price: 155, image: '/menu/seasonal-118.jpeg', badges: [], sortOrder: 2, available: true },
  { id: 'seasonal-119', categorySlug: 'seasonal', name: 'Гарбузовий лате', group: 'ГАРЯЧІ СЕЗОННІ НАПОІ', description: '', price: 95, image: '/menu/seasonal-119.jpeg', badges: [], sortOrder: 3, available: true },
  { id: 'seasonal-120', categorySlug: 'seasonal', name: 'Гарячий шоколад', group: 'ГАРЯЧІ СЕЗОННІ НАПОІ', description: '', price: 85, image: '/menu/seasonal-120.jpeg', badges: [], sortOrder: 4, available: true },
  { id: 'seasonal-121', categorySlug: 'seasonal', name: 'Irish coffe', group: 'АЛКОГОЛЬНІ ГАРЯЧІ НАПОІ', description: '', price: 155, image: '/menu/seasonal-121.jpeg', badges: [], sortOrder: 5, available: true },
  { id: 'seasonal-122', categorySlug: 'seasonal', name: 'Глінтвейн безалкогольний', group: 'ГАРЯЧІ СЕЗОННІ НАПОІ', description: '', price: 95, image: '/menu/seasonal-122.jpeg', badges: [], sortOrder: 6, available: true },
  { id: 'seasonal-123', categorySlug: 'seasonal', name: 'Bailyes coffe', group: 'АЛКОГОЛЬНІ ГАРЯЧІ НАПОІ', description: '', price: 155, image: '/menu/seasonal-123.jpeg', badges: [], sortOrder: 7, available: true },
  { id: 'seasonal-124', categorySlug: 'seasonal', name: 'Раф Баунті', group: 'ГАРЯЧІ СЕЗОННІ НАПОІ', description: '', price: 115, image: '/menu/seasonal-124.jpeg', badges: [], sortOrder: 8, available: true },
  { id: 'seasonal-125', categorySlug: 'seasonal', name: 'VERY BERRY', group: 'АЛКОГОЛЬНІ ГАРЯЧІ НАПОІ', description: '', price: 155, image: '/menu/seasonal-125.jpeg', badges: [], sortOrder: 9, available: true },
  { id: 'seasonal-126', categorySlug: 'seasonal', name: 'Капуоранж', group: 'ГАРЯЧІ СЕЗОННІ НАПОІ', description: '', price: 85, image: '', badges: [], sortOrder: 10, available: true },
  { id: 'seasonal-127', categorySlug: 'seasonal', name: 'Раф Чиз', group: 'ГАРЯЧІ СЕЗОННІ НАПОІ', description: '', price: 115, image: '', badges: [], sortOrder: 11, available: true },
  { id: 'seasonal-128', categorySlug: 'seasonal', name: 'Berry Splash безалкогольний', group: 'ГАРЯЧІ СЕЗОННІ НАПОІ', description: '', price: 155, image: '', badges: [], sortOrder: 12, available: true },
  { id: 'seasonal-129', categorySlug: 'seasonal', name: 'Айріш кава безалкогольна', group: 'ГАРЯЧІ СЕЗОННІ НАПОІ', description: '', price: 95, image: '', badges: [], sortOrder: 13, available: true },
  { id: 'seasonal-130', categorySlug: 'seasonal', name: 'Американо Чилі', group: 'ГАРЯЧІ СЕЗОННІ НАПОІ', description: '', price: 75, image: '', badges: [], sortOrder: 14, available: true },
];
